name: CI

on:
  push:
    branches: [develop, testing, feature/*, bugfix/*, hotfix/*, dev/*, main]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Backend Tests
        run: docker compose --profile test run backend-test

      - name: Run Web Tests
        run: docker compose --profile test run web-test

      - name: Run Web-Shop Tests
        run: docker compose --profile test run web-shop-test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: reports/
